name: Publishing

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test
      - name: Package
        run: | 
          cd /Core/PackDB.Core/bin/Release
          tree
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: /Core/PackDB.Core/PackDB.Core.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: PackDB.Core
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ github.NUGETAPIKEY }}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: # optional
